import type { Product } from "@/lib/types"

export const products: Product[] = [
  {
    id: "1",
    name: "LHood Signature Hoodie",
    description: "Premium heavyweight cotton hoodie with embroidered logo. Oversized fit with kangaroo pocket.",
    price: 89.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Hoodies",
    featured: true,
  },
  {
    id: "2",
    name: "Urban Streetwear Cap",
    description: "Adjustable cap with embroidered LHood logo. Perfect for any street style outfit.",
    price: 34.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Accessories",
    featured: true,
  },
  {
    id: "3",
    name: "Graphic Print T-Shirt",
    description: "100% organic cotton t-shirt with exclusive LHood graphic print. Relaxed fit.",
    price: 49.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "T-Shirts",
    featured: false,
  },
  {
    id: "4",
    name: "High-Top Sneakers",
    description: "Limited edition high-top sneakers with premium leather upper and custom LHood design.",
    price: 129.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Footwear",
    featured: true,
  },
  {
    id: "5",
    name: "Cargo Pants",
    description: "Tactical cargo pants with multiple pockets. Relaxed fit with adjustable waist.",
    price: 79.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Bottoms",
    featured: false,
  },
  {
    id: "6",
    name: "Crossbody Bag",
    description: "Water-resistant crossbody bag with multiple compartments and LHood logo patch.",
    price: 59.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Accessories",
    featured: false,
  },
  {
    id: "7",
    name: "Oversized Bomber Jacket",
    description: "Premium quality bomber jacket with embroidered details and satin lining.",
    price: 149.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Outerwear",
    featured: true,
  },
  {
    id: "8",
    name: "Beanie Hat",
    description: "Ribbed knit beanie with folded cuff and embroidered LHood logo.",
    price: 29.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Accessories",
    featured: false,
  },
]

